In [12]:
import pandas as pd

In [10]:
pd.__version__

'2.2.2'

In [24]:
d=[12,21,3,24,4,6]
ind=['r1','r2','r3','r4','r5','r6']
s=pd.Series(data=d)
s=pd.Series(data=d,index=ind,name='casas')
s

r1    12
r2    21
r3     3
r4    24
r5     4
r6     6
Name: casas, dtype: int64

In [36]:
# Exemplo 2: Com rótulos personalizados

# Lista com os valores médios de oxigênio dissolvido (em mg/L) em diferentes rios da Amazônia
oxigenio_dissolvido = [6.2, 5.8, 7.1]

# Lista com os nomes dos rios que servirão como rótulos (índices) da Series
nomes_rios = ['Rio Solimões', 'Rio Juruá', 'Rio Tocantins']

# Criação da Series: cada valor é associado ao nome do rio correspondente
# Isso facilita a leitura e a análise dos dados ambientais
serie_oxigenio = pd.Series(data=oxigenio_dissolvido, index=nomes_rios, name='O₂ Dissolvido (mg/L)')

# Exibe a Series completa com rótulos personalizados
print("Valores de oxigênio dissolvido por rio:")
print(serie_oxigenio)

# Acesso a um valor específico pelo nome do rio
print("\nOxigênio dissolvido no Rio Juruá:", serie_oxigenio['Rio Juruá'])

Valores de oxigênio dissolvido por rio:
Rio Solimões     6.2
Rio Juruá        5.8
Rio Tocantins    7.1
Name: O₂ Dissolvido (mg/L), dtype: float64

Oxigênio dissolvido no Rio Juruá: 5.8

In [32]:
s_res['Com. São João']

2.3

In [37]:
# Dicionário com dados ambientais: nome do rio como chave, pH médio como valor
dados_ph = {
    'Rio Amazonas': 6.9,
    'Rio Tapajós': 6.5,
    'Rio Madeira': 6.2
}

# Criação da Series usando o dicionário
serie_ph = pd.Series(dados_ph, name='pH Médio')

# Exibindo a Series
print(serie_ph)

Rio Amazonas    6.9
Rio Tapajós     6.5
Rio Madeira     6.2
Name: pH Médio, dtype: float64

In [47]:
#data frame
# Dados simulados de controle de ovos de tartaruga
dados = {
    'Ninho': ['N1', 'N2', 'N3', 'N4'],
    'Localização': ['Praia do Arumã', 'Ilha das Pedras', 'Praia do Juruá', 'Vila Mãe Terra'],
    'Espécie': ['Tartaruga-da-Amazônia', 'Iaçá', 'Tartaruga-da-Amazônia', 'Iaçá'],
    'Qtd Ovos': [85, 92, 78, 104],
    'Data Coleta': ['2025-07-01', '2025-07-02', '2025-07-03', '2025-07-04']
}

# Criando o DataFrame
df_ovos = pd.DataFrame(dados)
df_ovos

  Ninho      Localização                Espécie  Qtd Ovos Data Coleta
0    N1   Praia do Arumã  Tartaruga-da-Amazônia        85  2025-07-01
1    N2  Ilha das Pedras                   Iaçá        92  2025-07-02
2    N3   Praia do Juruá  Tartaruga-da-Amazônia        78  2025-07-03
3    N4   Vila Mãe Terra                   Iaçá       104  2025-07-04

In [50]:

# Dados de monitoramento dos ninhos de tartarugas
dados_nascimento = {
    'Ninho': ['N5', 'N6', 'N7', 'N8'],
    'Localização': ['Praia Verde', 'Ponta do Jabuti', 'Ilha do Arraial', 'Praia do Sol'],
    'Espécie': ['Tartaruga-da-Amazônia', 'Iaçá', 'Tartaruga-da-Amazônia', 'Iaçá'],
    'Previsão Nascimento': ['2025-08-10', '2025-08-12', '2025-08-15', '2025-08-18'],
    'Risco de Predação': ['Alto', 'Médio', 'Baixo', 'Médio']
}

# Criando o DataFrame
df_nascimento = pd.DataFrame(dados_nascimento)




# Exibindo o DataFrame
df_nascimento

,Ninho,Localização,Espécie,Previsão Nascimento,Risco de Predação
0,N5,Praia Verde,Tartaruga-da-Amazônia,2025-08-10,Alto
1,N6,Ponta do Jabuti,Iaçá,2025-08-12,Médio
2,N7,Ilha do Arraial,Tartaruga-da-Amazônia,2025-08-15,Baixo
3,N8,Praia do Sol,Iaçá,2025-08-18,Médio

In [51]:
dados = {
    'Espécie': ['Castanheira', 'Andiroba', 'Ipê Amarelo'],
    'Altura Média (m)': [25.5, 18.0, 12.3],
    'Protegida por Lei': [True, False, True]
}

df = pd.DataFrame(dados)

# Verificando os tipos de dados
print("Tipos de dados em cada coluna:")
print(df.dtypes)

Tipos de dados em cada coluna:
Espécie               object
Altura Média (m)     float64
Protegida por Lei       bool
dtype: object

In [59]:
caminho_arquivo = '/home/akel/PycharmProjects/I2A2/data/raw/qualidade_agua_amazonia.csv'

df = pd.read_csv(caminho_arquivo, sep=';',encoding='utf-8')

# Exibindo as primeiras linhas
print("Dados de Qualidade da Água na Amazônia:")
print(df.head())

Dados de Qualidade da Água na Amazônia:
           Rio   pH  Turbidez  Oxigênio Dissolvido
0    Rio Negro  6.3       1.2                  7.5
1  Rio Tapajós  7.0       2.5                  8.1
2  Rio Madeira  6.8       3.8                  7.9
3    Rio Xingu  5.9       0.9                  6.8
4    Rio Purus  6.5       2.1                  7.2

In [66]:
dados = {
    'Localização': ['Praia do Arumã', 'Ilha das Pedras', 'Praia do Juruá'],
    'Qtd Ovos': [85, 92, 78]
}

# Definindo o nome dos ninhos como índice
df = pd.DataFrame(dados, index=['N1', 'N2', 'N3'])

# Apresenta DataFrame
display(df)
#loc usa informação do nome do indice df.loc['name']
#iloc usa informacao posicao numerica df.iloc[ numero inteiro ]
# Acessando os dados do ninho N2 usando o método loc --
print("\nInformações do Ninho N2:")print(df.loc['N1'])

        Localização  Qtd Ovos
N1   Praia do Arumã        85
N2  Ilha das Pedras        92
N3   Praia do Juruá        78

Informações do Ninho N2:
Localização    Praia do Arumã
Qtd Ovos                   85
Name: N1, dtype: object

In [82]:
#selecionando colunas
df.loc[:,'Localização']
#ou 
df.iloc[:,1]

N1    85
N2    92
N3    78
Name: Qtd Ovos, dtype: int64

In [11]:
import pandas as pd

dados = {
    'Qtd Ovos': [85, 92, 78],
    'Temperatura (°C)': [29.5, 30.1, 28.7],
    'Umidade (%)': [88, 85, 90]
}

# Criando o DataFrame com rótulos personalizados para os ninhos
df = pd.DataFrame(dados, index=['N1', 'N2', 'N3'])

# Selecionando apenas os valores numéricos da linha do Ninho N2
valores_ovos_ninho = df.iloc[0]

# Calculando a média dos ovos
media_ovos = valores_ovos_ninho.mean()

# Exibindo os dados coletados
print(df,f"\n")


# Exibindo os valores e a média
print("\nMédia de Ovos Encontrados:", round(media_ovos, 2))

df.iloc[0].mean()

    Qtd Ovos  Temperatura (°C)  Umidade (%)
N1        85              29.5           88
N2        92              30.1           85
N3        78              28.7           90


Média de Ovos Encontrados: 67.5

67.5

In [13]:
import pandas as pd

# Dados simulados de área desmatada em hectares por município
dados = {
    'Área Desmatada (ha)': [120.5, 85.3, 210.7],
    'Ano': [2023, 2023, 2023]
}

# Criando o DataFrame com nomes de municípios como índice
df = pd.DataFrame(dados, index=['Cametá', 'Altamira', 'Itaituba'])
display(df)
# Localizando o valor de área desmatada em Altamira
area_cameta = df.loc['Cametá', 'Área Desmatada (ha)']

# Exibindo o resultado
print("Área desmatada em Cametá:", area_cameta, "hectares")

          Área Desmatada (ha)   Ano
Cametá                  120.5  2023
Altamira                 85.3  2023
Itaituba                210.7  2023

Área desmatada em Cametá: 120.5 hectares

In [51]:
# Leitura dos dados ambientais
caminho_arquivo = '/home/akel/PycharmProjects/I2A2/data/raw/qualidade_agua_amazonia.csv'

df = pd.read_csv(caminho_arquivo, sep=';',encoding='utf-8')
display(df)
# Filtrando rios com pH abaixo de 6.5 E turbidez acima de 2.0
rios_criticos = df[(df['pH'] < 6.5) & (df['Turbidez'] > 2.0)]



rios_filtrados = df.query("pH <= 6.5 and Turbidez > 2.0 and `Oxigênio Dissolvido` <= 7.5")

# # Exibindo o resultado
# print("Rios com pH abaixo de 6.5,turbidez acima de 2.0 e Oxigênio Dissolvido <=7.5:\n")
# print(rios_filtrados)

# # # Exibindo os rios que atendem ambas as condições
# print("Rios com pH < 6.5 e Turbidez > 2.0:")
# print("="*60)
# print(rios_criticos)

df.loc[:,'pH']

           Rio   pH  Turbidez  Oxigênio Dissolvido
0    Rio Negro  6.3       1.2                  7.5
1  Rio Tapajós  7.0       2.5                  8.1
2  Rio Madeira  6.8       3.8                  7.9
3    Rio Xingu  5.9       0.9                  6.8
4    Rio Purus  6.5       2.1                  7.2

0    6.3
1    7.0
2    6.8
3    5.9
4    6.5
Name: pH, dtype: float64

Atividade 1
Você acaba de receber um arquivo com registros ambientais coletados em campo por equipes de monitoramento. Ele contém informações sobre espécies de macacos observadas na Amazônia, com dados como quantidade de indivíduos, localização, temperatura, umidade e se a espécie é alvo de conservação.
Utilize a linguagem Python e a biblioteca pandas para carregar o arquivo CSV intitulado observacao_macacos_natura.csv e exibir as 5 primeiras linhas da tabela.

In [54]:
caminho_arquivo = '/home/akel/PycharmProjects/I2A2/data/raw/observacao_macacos_natura.csv'

df = pd.read_csv(caminho_arquivo)
df.head()

,ID,Espécie,Local de Observação,Qtd Indivíduos,Temperatura Média (°C),Umidade Média (%),Alvo de Conservação
0,M001,Macaco-aranha,Serra do Divisor,1,28.7,77,Não
1,M002,Macaco-aranha,Reserva Mamirauá,11,27.3,84,Não
2,M003,Macaco-prego,APA Marajó,9,29.2,84,Sim
3,M004,Zogue-zogue,Parque Anavilhanas,8,28.8,81,Sim
4,M005,Macaco-aranha,Serra do Divisor,3,30.3,85,Sim

A floresta está em alerta! Precisamos identificar apenas os registros em que as espécies estão marcadas como "Alvo de Conservação".¶
Crie um código que filtre o DataFrame e exiba somente os registros onde a coluna Alvo de Conservação seja igual a "Sim". Exiba o total de registros encontrados

In [61]:
df_consr=df[df['Alvo de Conservação']=='Sim']
N=len(df_consr)
N

21

Algumas regiões da Amazônia apresentaram temperaturas ambientais acima do limite de segurança para determinadas espécies.
Filtre e exiba os locais onde a Temperatura Média foi superior a 30.0°C. Utilize o método query() ou uma condição com o operador >

In [69]:
temp_lim=df[df['Temperatura Média (°C)']>30]
temp_LIMITE=df.query('`Temperatura Média (°C)` >30')
len(temp_LIMITE)

8

Atividade 4 - Cruzando Temperatura e Umidade
Queremos saber quais registros indicam alta temperatura e baixa umidade, condições preocupantes para a sobrevivência de primatas.
Utilize duas condições ao mesmo tempo: selecione os registros onde Temperatura Média (°C) seja maior que 30 e Umidade Média (%) menor que 80. Exiba o resultado.

In [75]:
temp_umd=df[ (df['Temperatura Média (°C)']>30) & (df['Umidade Média (%)']<80) ]
temp_UMD=df.query('`Temperatura Média (°C)` >30 and `Umidade Média (%)`<80')

temp_UMD

,ID,Espécie,Local de Observação,Qtd Indivíduos,Temperatura Média (°C),Umidade Média (%),Alvo de Conservação
13,M014,Zogue-zogue,Floresta Tapajós,3,30.2,76,Não
24,M025,Cuxiú,Floresta Tapajós,6,30.4,78,Sim

Um pesquisador quer investigar apenas os dados de um determinado local, por exemplo: "Reserva Mamirauá".
Peça ao usuário que digite o nome de um local de observação e filtre o DataFrame para mostrar os registros apenas daquele local. Use o método .isin() ou .str.contains().

In [106]:
df[df['Local de Observação'].isin(['Floresta Tapajós'])]

df[df['Local de Observação']=='Floresta Tapajós']
# str.contains permite encontrar variações o termo,mudando case sensitive. etc.
df[df['Local de Observação'].str.contains(r'\bFloresta Tapajós\b',case=True,na=False)]
df

,ID,Espécie,Local de Observação,Qtd Indivíduos,Temperatura Média (°C),Umidade Média (%),Alvo de Conservação
0,M001,Macaco-aranha,Serra do Divisor,1,28.7,77,Não
1,M002,Macaco-aranha,Reserva Mamirauá,11,27.3,84,Não
2,M003,Macaco-prego,APA Marajó,9,29.2,84,Sim
3,M004,Zogue-zogue,Parque Anavilhanas,8,28.8,81,Sim
4,M005,Macaco-aranha,Serra do Divisor,3,30.3,85,Sim
5,M006,Macaco-prego,APA Marajó,4,29.4,82,Sim
6,M007,Zogue-zogue,APA Marajó,5,27.0,91,Sim
7,M008,Macaco-prego,APA Marajó,10,27.9,95,Sim
8,M009,Uacari,Parque Anavilhanas,10,27.7,76,Sim
9,M010,Macaco-aranha,Reserva Mamirauá,8,27.3,94,Não
10,M011,Macaco-aranha,Parque Anavilhanas,7,31.2,88,Não
11,M012,Cuxiú,Floresta Tapajós,8,29.2,91,Sim
12,M013,Uacari,Serra do Divisor,2,27.4,84,Não
13,M014,Zogue-zogue,Floresta Tapajós,3,30.2,76,Não
14,M015,Macaco-prego,APA Marajó,10,29.3,79,Sim
15,M016,Zogue-zogue,Reserva Mamirauá,3,27.9,90,Sim
16,M017,Macaco-aranha,Floresta Tapajós,3,26.5,91,Não
17,M018,Zogue-zogue,APA Marajó,9,31.1,83,Sim
18,M019,Zogue-zogue,APA Marajó,2,30.2,93,Não
19,M020,Uacari,Floresta Tapajós,3,30.0,82,Não
20,M021,Cuxiú,APA Marajó,5,27.9,82,Não
21,M022,Macaco-prego,Serra do Divisor,4,29.4,89,Não
22,M023,Macaco-prego,Reserva Mamirauá,6,27.7,90,Não
23,M024,Uacari,Parque Anavilhanas,1,26.9,94,Não
24,M025,Cuxiú,Floresta Tapajós,6,30.4,78,Sim
25,M026,Macaco-aranha,APA Marajó,8,29.7,92,Sim
26,M027,Zogue-zogue,Reserva Mamirauá,12,28.8,87,Não
27,M028,Uacari,Floresta Tapajós,8,27.9,93,Sim
28,M029,Uacari,APA Marajó,4,29.6,80,Não
29,M030,Zogue-zogue,Parque Anavilhanas,6,29.4,88,Não
30,M031,Zogue-zogue,Parque Anavilhanas,3,30.1,89,Não
31,M032,Macaco-prego,APA Marajó,7,29.5,90,Não
32,M033,Cuxiú,Floresta Tapajós,5,27.0,78,Não
33,M034,Uacari,Serra do Divisor,12,27.5,84,Sim
34,M035,Macaco-aranha,APA Marajó,6,29.9,85,Não
35,M036,Zogue-zogue,Reserva Mamirauá,1,29.6,84,Não
36,M037,Macaco-prego,Reserva Mamirauá,12,27.1,93,Não
37,M038,Uacari,Floresta Tapajós,3,27.5,86,Sim
38,M039,Macaco-prego,Floresta Tapajós,10,28.3,83,Não
39,M040,Cuxiú,Reserva Mamirauá,7,28.7,94,Não
40,M041,Macaco-prego,Floresta Tapajós,4,29.8,79,Sim
41,M042,Zogue-zogue,Parque Anavilhanas,11,29.1,88,Não
42,M043,Cuxiú,APA Marajó,6,29.5,85,Sim
43,M044,Macaco-aranha,Floresta Tapajós,3,26.7,81,Não
44,M045,Cuxiú,APA Marajó,4,27.3,84,Não
45,M046,Zogue-zogue,Parque Anavilhanas,10,27.0,82,Não
46,M047,Cuxiú,Serra do Divisor,3,28.7,95,Sim
47,M048,Uacari,Parque Anavilhanas,9,30.8,91,Sim
48,M049,Macaco-aranha,Serra do Divisor,6,29.6,95,Sim
49,M050,Macaco-prego,Serra do Divisor,9,28.1,95,Não

Atividade 6 - Atualizando Dados de Campo
Durante a checagem, foi descoberto que um dos registros tinha a quantidade de indivíduos informada incorretamente.
Escolha um registro específico (ex: ID = "M010") e atualize o valor da coluna Qtd Indivíduos para um novo número (à sua escolha). Em seguida, exiba a linha alterada.

In [136]:
# Exibindo os primeiros IDs disponíveis na base

print("Alguns IDs disponíveis para atualização:\n")
display(df.head())

id_alvo = input("\nDigite o ID do registro a ser corrigido (ex: M010): ")

if id_alvo in df['ID'].values:
    novo_qt = int(input("Digite o novo valor para 'Qtd Indivíduos': "))
    
    df.loc[df['ID']==id_alvo,'Qtd Indivíduos']=novo_qt
    print(f"\nRegistro do ID {id_alvo} atualizado com sucesso:")
    print(df[df['ID'] == id_alvo])
else:
    print(f"\nID '{id_alvo}' não encontrado na base de dados.")


    

# #df.loc[,'Qtd Indivíduos']

# #df[df['ID']==M001

# #df[df['ID']=='M001']
# df.loc[df['ID']=='M002','Qtd Indivíduos']=11
# df.loc[df['ID']=='M002','Qtd Indivíduos']

Alguns IDs disponíveis para atualização:

,ID,Espécie,Local de Observação,Qtd Indivíduos,Temperatura Média (°C),Umidade Média (%),Alvo de Conservação
0,M001,Macaco-aranha,Serra do Divisor,1,28.7,77,Não
1,M002,Macaco-aranha,Reserva Mamirauá,11,27.3,84,Não
2,M003,Macaco-prego,APA Marajó,9,29.2,84,Sim
3,M004,Zogue-zogue,Parque Anavilhanas,8,28.8,81,Sim
4,M005,Macaco-aranha,Serra do Divisor,3,30.3,85,Sim

Digite o ID do registro a ser corrigido (ex: M010):  M001
Digite o novo valor para 'Qtd Indivíduos':  8

Registro do ID M001 atualizado com sucesso:
     ID        Espécie Local de Observação  Qtd Indivíduos  \
0  M001  Macaco-aranha    Serra do Divisor               8

   Temperatura Média (°C)  Umidade Média (%) Alvo de Conservação
0                    28.7                 77                 Não

In [137]:
df

,ID,Espécie,Local de Observação,Qtd Indivíduos,Temperatura Média (°C),Umidade Média (%),Alvo de Conservação
0,M001,Macaco-aranha,Serra do Divisor,8,28.7,77,Não
1,M002,Macaco-aranha,Reserva Mamirauá,11,27.3,84,Não
2,M003,Macaco-prego,APA Marajó,9,29.2,84,Sim
3,M004,Zogue-zogue,Parque Anavilhanas,8,28.8,81,Sim
4,M005,Macaco-aranha,Serra do Divisor,3,30.3,85,Sim
5,M006,Macaco-prego,APA Marajó,4,29.4,82,Sim
6,M007,Zogue-zogue,APA Marajó,5,27.0,91,Sim
7,M008,Macaco-prego,APA Marajó,10,27.9,95,Sim
8,M009,Uacari,Parque Anavilhanas,10,27.7,76,Sim
9,M010,Macaco-aranha,Reserva Mamirauá,8,27.3,94,Não
10,M011,Macaco-aranha,Parque Anavilhanas,7,31.2,88,Não
11,M012,Cuxiú,Floresta Tapajós,8,29.2,91,Sim
12,M013,Uacari,Serra do Divisor,2,27.4,84,Não
13,M014,Zogue-zogue,Floresta Tapajós,3,30.2,76,Não
14,M015,Macaco-prego,APA Marajó,10,29.3,79,Sim
15,M016,Zogue-zogue,Reserva Mamirauá,3,27.9,90,Sim
16,M017,Macaco-aranha,Floresta Tapajós,3,26.5,91,Não
17,M018,Zogue-zogue,APA Marajó,9,31.1,83,Sim
18,M019,Zogue-zogue,APA Marajó,2,30.2,93,Não
19,M020,Uacari,Floresta Tapajós,3,30.0,82,Não
20,M021,Cuxiú,APA Marajó,5,27.9,82,Não
21,M022,Macaco-prego,Serra do Divisor,4,29.4,89,Não
22,M023,Macaco-prego,Reserva Mamirauá,6,27.7,90,Não
23,M024,Uacari,Parque Anavilhanas,1,26.9,94,Não
24,M025,Cuxiú,Floresta Tapajós,6,30.4,78,Sim
25,M026,Macaco-aranha,APA Marajó,8,29.7,92,Sim
26,M027,Zogue-zogue,Reserva Mamirauá,12,28.8,87,Não
27,M028,Uacari,Floresta Tapajós,8,27.9,93,Sim
28,M029,Uacari,APA Marajó,4,29.6,80,Não
29,M030,Zogue-zogue,Parque Anavilhanas,6,29.4,88,Não
30,M031,Zogue-zogue,Parque Anavilhanas,3,30.1,89,Não
31,M032,Macaco-prego,APA Marajó,7,29.5,90,Não
32,M033,Cuxiú,Floresta Tapajós,5,27.0,78,Não
33,M034,Uacari,Serra do Divisor,12,27.5,84,Sim
34,M035,Macaco-aranha,APA Marajó,6,29.9,85,Não
35,M036,Zogue-zogue,Reserva Mamirauá,1,29.6,84,Não
36,M037,Macaco-prego,Reserva Mamirauá,12,27.1,93,Não
37,M038,Uacari,Floresta Tapajós,3,27.5,86,Sim
38,M039,Macaco-prego,Floresta Tapajós,10,28.3,83,Não
39,M040,Cuxiú,Reserva Mamirauá,7,28.7,94,Não
40,M041,Macaco-prego,Floresta Tapajós,4,29.8,79,Sim
41,M042,Zogue-zogue,Parque Anavilhanas,11,29.1,88,Não
42,M043,Cuxiú,APA Marajó,6,29.5,85,Sim
43,M044,Macaco-aranha,Floresta Tapajós,3,26.7,81,Não
44,M045,Cuxiú,APA Marajó,4,27.3,84,Não
45,M046,Zogue-zogue,Parque Anavilhanas,10,27.0,82,Não
46,M047,Cuxiú,Serra do Divisor,3,28.7,95,Sim
47,M048,Uacari,Parque Anavilhanas,9,30.8,91,Sim
48,M049,Macaco-aranha,Serra do Divisor,6,29.6,95,Sim
49,M050,Macaco-prego,Serra do Divisor,9,28.1,95,Não